[admission_control]
address = "0.0.0.0:65350"
need_to_check_mempool_before_validation = false
max_concurrent_inbound_syncs = 100

[admission_control.upstream_proxy_timeout]
secs = 1
nanos = 0

[rpc]
address = "0.0.0.0:65362"

[base]
data_dir = "./0_dev_config/0"
role = "validator"

[base.waypoint]
type = "from_config"

[base.waypoint.waypoint]
version = 0
value = "6065c18ea57502d3a8a5dfe48c69671dca52ee10a8161ef3d0da6d393fa23e89"

[consensus]
max_block_size = 1000
contiguous_rounds = 2
max_pruned_blocks_in_mem = 10000
round_initial_timeout_ms = 1000

[consensus.proposer_type]
type = "leader_reputation"
active_weights = 99
inactive_weights = 1
[consensus.safety_rules.backend]
type = "in_memory_storage"

[consensus.safety_rules.service]
type = "thread"

[debug_interface]
admission_control_node_debug_port = 65352
metrics_server_port = 65354
public_metrics_server_port = 65356
address = "0.0.0.0"

[execution]
genesis_file_location = "genesis.blob"

[execution.service]
type = "thread"

[logger]
is_async = true
chan_size = 256
level = "INFO"

[metrics]
collection_interval_ms = 1000
dir = "metrics"
enabled = false

[mempool]
broadcast_transactions = true
shared_mempool_tick_interval_ms = 50
shared_mempool_batch_size = 100
shared_mempool_max_concurrent_inbound_syncs = 100
max_broadcasts_per_peer = 25
capacity = 1000000
capacity_per_user = 100
system_transaction_timeout_secs = 86400
system_transaction_gc_interval_ms = 180000

[state_sync]
chunk_limit = 250
tick_interval_ms = 100
long_poll_timeout_ms = 30000
max_chunk_limit = 1000
max_timeout_ms = 120000
sync_request_timeout_ms = 60000

[storage]
address = "127.0.0.1:65358"
backup_service_port = 65360
dir = "libradb/db"
grpc_max_receive_len = 100000000

[test]
auth_key = "1796824cdcc3ab205c25f260e15dc6705942d356f114089d4a46f2f3b0b15b52"
operator_private_key = "da3599e23bd8dd79ce77578fc791a72323de545cf23bb1588e49d8a1e023f6f3"
consensus_private_key = "50e53de2ca2006b933a4053cf4766c20ff773570e4af2d9d6ebca5ef02a49840"
initialize_storage = true

[upstream]
primary_networks = ["5942d356f114089d4a46f2f3b0b15b52"]
upstream_peers = []
fallback_networks = []

[validator_network]
listen_address = "/ip4/0.0.0.0/tcp/65364"
advertised_address = "/ip4/0.0.0.0/tcp/65364"
discovery_interval_ms = 1000
connectivity_check_interval_ms = 5000
enable_remote_authentication = true
discovery_method = "gossip"
network_peers_file = ""
seed_peers_file = "5942d356f114089d4a46f2f3b0b15b52.seed_peers.toml"

[validator_network.identity]
type = "from_config"
key = "e8485074628c5cde1b9c58b70a90b7de778cbdfc6148044f4373008dacd9bc5d"
peer_id = "5942d356f114089d4a46f2f3b0b15b52"

[validator_network.network_id]
type = "Validator"
