[package]
name = "vm-validator"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem vm validator"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
fail = "0.4.0"
scratchpad = { path = "../storage/scratchpad" }
diem-state-view = { path = "../storage/state-view" }
storage-interface = { path = "../storage/storage-interface" }
diem-types = { path = "../types" }
diem-vm = { path = "../diem-move/diem-vm" }
diem-workspace-hack = { version = "0.1", path = "../crates/diem-workspace-hack" }

[dev-dependencies]
rand = "0.8.3"

executor = { path = "../execution/executor" }
executor-test-helpers = { path = "../execution/executor-test-helpers" }
diem-crypto = { path = "../crates/diem-crypto", features = ["fuzzing"] }
diem-temppath = { path = "../crates/diem-temppath" }
diem-types = { path = "../types", features = ["fuzzing"] }
diem-vm = { path = "../diem-move/diem-vm" }
diemdb = { path = "../storage/diemdb", features = ["fuzzing"] }
storage-service = { path = "../storage/storage-service" }
diem-transaction-builder = { path = "../sdk/transaction-builder" }
vm-genesis = { path = "../diem-move/vm-genesis" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }

[features]
default = []
failpoints = ["fail/failpoints"]
fuzzing = ["diem-types/fuzzing", "diem-crypto/fuzzing", "diemdb/fuzzing"]
