[package]
name = "diem-validator-interface"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Defines interfaces between the diem nodes and local move infrastructure"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
diem-config = { path = "../../config" }
diem-client = { path = "../../crates/diem-client" }
diem-types = { path = "../../types" }
diemdb = { path = "../../storage/diemdb" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
storage-interface = { path = "../../storage/storage-interface" }
scratchpad = { path = "../../storage/scratchpad" }
diem-state-view = { path = "../../storage/state-view" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "5ff91d82a4969f1efa18dfc18965a37300d8f2e4" }
bcs = "0.1.2"
