[package]
name = "diem-github-client"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
repository = "https://github.com/diem/diem"
description = "Diem's Restful GitHub Client"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = { version = "1.0.116", features = ["derive"], default-features = false }
serde_json = "1.0.58"
thiserror = "1.0.21"
ureq = { version = "1.5.1", features = ["json", "native-tls"], default-features = false }

diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }

[dev-dependencies]
base64 = "0.13.0"
