[package]
name = "netcore"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem netcore"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.41"
bytes = "0.5.6"
futures = "0.3.6"
pin-project = "0.4.26"
serde = { version = "1.0.116", default-features = false }
tokio = { version = "0.2.22", features = ["full"] }

diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
diem-network-address = { path = "../network-address", version = "0.1.0" }
diem-types = { path = "../../types" }
memsocket = { path = "../memsocket", version = "0.1.0", optional = true }

[dev-dependencies]
diem-logger = { path = "../../common/logger", version = "0.1.0" }
memsocket = { path = "../memsocket", version = "0.1.0" }

[features]
default = []
fuzzing = ["memsocket/fuzzing"]
testing = ["memsocket/testing"]
