[package]
name = "diem-transaction-benchmarks"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem transaction benchmarks"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
criterion = "0.3.4"
proptest = "1.0.0"
criterion-cpu-time = "0.1.0"

diem-types = { path = "../../types", features = ["fuzzing"] }
language-e2e-tests = { path = "../e2e-tests" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
diem-crypto = { path = "../../crates/diem-crypto" }

read-write-set = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
read-write-set-dynamic = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
diem-vm = { path = "../diem-vm" }
diem-framework-releases = { path = "../diem-framework/DPN/releases" }

[[bench]]
name = "transaction_benches"
harness = false
