[package]
name = "diem-state-view"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem state view"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
