[package]
name = "DPNFramework"
version = "1.5.0"

[addresses]
Std = "0x1"
DiemFramework = "0x1"
DiemRoot = "0x0" #//////// 0L ////////
TreasuryCompliance = "0x0" #//////// 0L ////////
CurrencyInfo = "0x0" #//////// 0L ////////
VMReserved = "0x0"
BurnAddress = "0x0" #//////// 0L ////////

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
