[package]
name = "_transaction-builder"
version = "0.1.0"
edition = "2018"

[dependencies]
once_cell = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
diem-types = { path = "../diem-types", version = "0.1.0" }
