[package]
name = "x-core"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
description = "Core data structures used by x"
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
guppy = "0.5.0"
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
toml = "0.5.6"
once_cell = "1.4.1"
rental = "0.5.5"
serde = { version = "1.0.116", features = ["derive"] }
