[admission_control]
address = "0.0.0.0:8000"
need_to_check_mempool_before_validation = false
max_concurrent_inbound_syncs = 100

[admission_control.upstream_proxy_timeout]
secs = 1
nanos = 0

[rpc]
address = "0.0.0.0:8080"

[base]
data_dir = "./"
role = "validator"


[base.waypoint]
type = "from_config"

[base.waypoint.waypoint]
version = 0
value = "c20d50e14ca7cd0ef8fc209033f3f9ef7c0d0a169267cea8ec4ccda942868e19"

[consensus]
max_block_size = 1000
contiguous_rounds = 2
max_pruned_blocks_in_mem = 10000
round_initial_timeout_ms = 1000

[consensus.proposer_type]
type = "leader_reputation"
active_weights = 99
inactive_weights = 1

[consensus.safety_rules.backend]
type = "on_disk_storage"
path = "./key_store.json"
namespace = "lucas"

[consensus.safety_rules.service]
type = "thread"

[debug_interface]
admission_control_node_debug_port = 6191
metrics_server_port = 9101
public_metrics_server_port = 9102
address = "0.0.0.0"

[execution]
genesis_file_location = "genesis.blob"

[execution.service]
type = "thread"

# NOTE: Full node networks not used in libra-swarm tests.
# [[full_node_networks]]
# listen_address = "/ip4/0.0.0.0/tcp/6179"
# advertised_address = "/ip4/104.131.20.59/tcp/6179"
# discovery_interval_ms = 1000
# connectivity_check_interval_ms = 5000
# enable_remote_authentication = true
# discovery_method = "onchain"
# network_peers_file = ""
# seed_peers_file = "00000000000000000000000000000000.seed_peers.toml"
#
# [full_node_networks.identity]
# type = "from_storage"
# key_name = "fullnode_network"
# peer_id_name = "operator_account"
#
# [full_node_networks.identity.backend]
# type = "on_disk_storage"
# path = "./key_store.json"
# namespace = "lucas"
#
# [full_node_networks.network_id]
# type = "Private"
# name = "VFN"

[logger]
is_async = true
chan_size = 256
level = "INFO"

[metrics]
collection_interval_ms = 1000
dir = "metrics"
enabled = false

[mempool]
broadcast_transactions = true
shared_mempool_tick_interval_ms = 50
shared_mempool_batch_size = 100
shared_mempool_max_concurrent_inbound_syncs = 100
max_broadcasts_per_peer = 25
capacity = 1000000
capacity_per_user = 100
system_transaction_timeout_secs = 86400
system_transaction_gc_interval_ms = 180000

[state_sync]
chunk_limit = 250
tick_interval_ms = 100
long_poll_timeout_ms = 30000
max_chunk_limit = 1000
max_timeout_ms = 120000
sync_request_timeout_ms = 60000

[storage]
address = "127.0.0.1:6666"
backup_service_port = 7777
dir = "libradb/db"
grpc_max_receive_len = 100000000

# [test]
# auth_key = "30ea4cece204decfc0033ee5d960f34a21507b59b6e7f1b72c009036682736b7"
# operator_private_key = "8e23c03b0a957f636356a6ae092c18a82f9698d438f57e252fb9c6e67a668967"
# consensus_private_key = "982493856595fe10288cb9a346f8aa66bc07f815a418a791240af2445ce59719"
# initialize_storage = true

[upstream]
primary_networks = []
upstream_peers = []
fallback_networks = []

# [upstream]
# primary_networks = ["21507b59b6e7f1b72c009036682736b7"]
# upstream_peers = []
# fallback_networks = []


[validator_network]
listen_address = "/ip4/0.0.0.0/tcp/6180"
advertised_address = "/ip4/104.131.20.59/tcp/6180"
discovery_interval_ms = 1000
connectivity_check_interval_ms = 5000
enable_remote_authentication = true
discovery_method = "onchain"
# network_peers_file = ""
# seed_peers_file = "00000000000000000000000000000000.seed_peers.toml"

# seed_peers_file = "21507b59b6e7f1b72c009036682736b7.seed_peers.toml"

[validator_network.identity]
type = "from_storage"
key_name = "validator_network"
peer_id_name = "operator_account"

# [validator_network.identity]
# type = "from_config"
# key = "58e2de580b951eaf45b1cf9f231e592a02be15edf9f89394e1705bf0dce7b86c"
# peer_id = "21507b59b6e7f1b72c009036682736b7"

[validator_network.identity.backend]
type = "on_disk_storage"
path = "./key_store.json"
namespace = "lucas"

[validator_network.network_id]
type = "Validator"

[configs_ol_miner]
preimage = ""
proof = ""
