[package]
name = "many-keys-stress-test"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem channel"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.6"
channel = { path = "../", version = "0.1.0" }
diem-workspace-hack = { path = "../../workspace-hack", version = "0.1.0" }
structopt = "0.3.18"
