name: Integration

on:
  push:
    branches: [ main, ci, v5 ]
  pull_request:
    branches: [ main, 'release**', v5]
    
jobs:
  integration:
    name: Integration
    runs-on: self-hosted
    timeout-minutes: 90
    env:
      NODE_ENV: test
      TEST: y
    steps:
      - uses: actions/checkout@v2
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.52.1
            override: true
            components: rustfmt, clippy
      - name: Install deps
        run: sudo apt-get install -y lld
      - name: Check branch
        run: echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: Build sdlib
        run: cargo r -p diem-framework --release
      - name: MINING
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-mining.mk test
      - name: AUTOPAY percent-change
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-autopay.mk test-percent-bal
      - name: AUTOPAY fixed-once
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-autopay.mk test-fixed-once
      - name: AUTOPAY all
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-autopay.mk test
      - name: ONBOARD
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-onboard.mk test
      - name: File permissions
        run: sudo chmod -R 777 language/*
      - name: UPGRADE
        run: BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }} RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-upgrade.mk test
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: UPGRADE_NODE_LOG
          # A file, directory or wildcard pattern that describes what to upload
          path: $HOME/.0L/swarm_temp/logs/0.log
          # The desired behavior if no files are found using the provided path.
          warn: Output a warning but do not fail the action
          retention-days: 1


